stages:
  split:
    cmd: python split.py photos.csv photos-train.csv photos-test.csv
    deps:
    - photos.csv
    - split.py
    params:
    - prepare.min_split
    - prepare.num_est
    outs:
    - photos-test.csv
    - photos-train.csv
  featurize:
    cmd: python featurize.py photos-train.csv photos-train-feats.csv
    deps:
    - featurize.py
    - photos-train.csv
    params:
    - featurize.batch_size
    - featurize.estimators
    - featurize.layers
    - featurize.sample
    - featurize.tags
    - featurize.trees
    outs:
    - photos-train-feats.csv
  train:
    cmd: python train.py photos-train-feats.csv model.json
    deps:
    - photos-train-feats.csv
    - train.py
    params:
    - model.columns
    - model.estimators
    - model.features
    - model.sample
    - model.split
    - train.features
    - train.layers
    - train.num_est
    - train.random_state
    - train.weight_factor
    - validation.batch_size
    - validation.features
    - validation.max_depth
    - validation.random_state
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json photos-test.csv
    deps:
    - evaluate.py
    - model.json
    - photos-test.csv
    metrics:
    - metrics.json:
        cache: false
