stages:
  split:
    cmd: python split.py photos.csv photos-train.csv photos-test.csv
    deps:
    - photos.csv
    - split.py
    outs:
    - photos-test.csv
    - photos-train.csv
  featurize:
    cmd: python featurize.py photos-train.csv photos-train-feats.csv
    deps:
    - featurize.py
    - photos-train.csv
    outs:
    - photos-train-feats.csv
  train:
    cmd: python train.py photos-train-feats.csv model.json
    deps:
    - photos-train-feats.csv
    - train.py
    params:
    - batch_size
    - columns
    - epochs
    - estimators
    - folds
    - layers
    - max_depth
    - min_split
    - random_state
    - sample
    - seed
    - weight_factor
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json photos-test.csv
    deps:
    - evaluate.py
    - model.json
    - photos-test.csv
    metrics:
    - metrics.json:
        cache: false
