prepare:
  features: 1296
  folds: 11
  seed: 673551947
  random_state: 1024643724
model:
  batch_size: 16
  folds: 9
  max_depth: 16
  trees: 12
  ngrams: 4
  columns: 15
  drop: 0.3
  threads: 29
preprocessing:
  learning_rate: 0.1
  min_features: 3250
  threads: 15
  features: 3700
  random_state: 274000000
  passes: 54
  max_features: 3550
featurize:
  ngrams: 7
  min_split: 70
  dense: 121
  max_depth: 4
  learning_rate: 0.05646
concurrent:
  layers: 6
  columns: 12
  random_state: 150000000
  num_est: 150
  ngrams: 4
