stages:
  split:
    cmd: python split.py series.csv series-train.csv series-test.csv
    deps:
    - series.csv
    - split.py
    outs:
    - series-test.csv
    - series-train.csv
  featurize:
    cmd: python featurize.py series-train.csv series-train-feats.csv
    deps:
    - featurize.py
    - series-train.csv
    params:
    - featurize.batch_size
    - featurize.columns
    - featurize.dense
    - featurize.min_split
    - featurize.ngrams
    - featurize.passes
    - featurize.random_state
    - featurize.seed
    - featurize.threads
    - featurize.weight_factor
    outs:
    - series-train-feats.csv
  train:
    cmd: python train.py series-train-feats.csv model.json
    deps:
    - series-train-feats.csv
    - train.py
    params:
    - model.batch_size
    - model.columns
    - model.epochs
    - model.max_features
    - model.min_split
    - model.random_state
    - model.sample
    - model.weight_factor
    - settings.folds
    - settings.num_est
    - tagging.folds
    - tagging.min_split
    - tagging.seed
    - tagging.threads
    - validation.batch_size
    - validation.layers
    - validation.max_features
    - validation.min_split
    - validation.ngrams
    - validation.num_est
    - validation.sample
    - validation.split
    - validation.weight_factor
    outs:
    - model.json
  evaluate:
    cmd: python evaluate.py model.json series-test.csv
    deps:
    - evaluate.py
    - model.json
    - series-test.csv
    metrics:
    - metrics.json:
        cache: false
